# Generated by Django 3.1 on 2021-04-22 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert_scraper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapedalert',
            name='alert_type',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
