# Generated by Django 3.1 on 2021-04-28 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert_scraper', '0002_scrapedalert_alert_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapedalert',
            name='alert_data',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
