# Generated by Django 3.0.5 on 2020-05-05 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skip', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert',
            old_name='topic_id',
            new_name='topic',
        ),
    ]
