# Generated by Django 3.1 on 2020-08-10 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='message',
            field=models.JSONField(),
        ),
    ]
