# Generated by Django 3.1.1 on 2020-10-21 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skip', '0003_auto_20200810_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='message_extras',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='alert',
            name='message',
            field=models.JSONField(default=dict),
        ),
    ]
