# Generated by Django 3.1 on 2021-04-27 17:12

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skip', '0005_auto_20201021_0040'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventAttributesVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attributes', models.JSONField(default=dict)),
                ('tag', models.CharField(max_length=200)),
                ('sequence_number', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='alert',
            name='parsed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_identifier', models.CharField(max_length=200)),
                ('event_attributes', models.JSONField(default=dict)),
                ('localization', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('event_attributes_version', models.ManyToManyField(to='skip.EventAttributesVersion')),
            ],
        ),
        migrations.AddField(
            model_name='alert',
            name='event',
            field=models.ManyToManyField(to='skip.Event'),
        ),
    ]
