# Generated by Django 3.1 on 2021-04-27 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skip', '0006_auto_20210427_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_attributes',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_attributes_version',
        ),
        migrations.RemoveField(
            model_name='event',
            name='localization',
        ),
        migrations.AddField(
            model_name='eventattributesversion',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='skip.event'),
            preserve_default=False,
        ),
    ]
