# Generated by Django 3.1 on 2021-04-28 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skip', '0008_auto_20210428_1603'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventAttributesVersion',
            new_name='EventAttributes',
        ),
    ]
