# Generated by Django 3.1 on 2021-04-30 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skip', '0009_auto_20210428_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='extracted_fields',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='role',
        ),
        migrations.AddField(
            model_name='alert',
            name='raw_message',
            field=models.JSONField(default=dict),
        ),
    ]
