# Generated by Django 3.1 on 2021-04-30 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skip', '0010_auto_20210430_1642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert',
            old_name='message',
            new_name='parsed_message',
        ),
    ]
