# Generated by Django 3.1 on 2021-04-30 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skip', '0011_auto_20210430_1746'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='alert',
            name='alert_timestamp_idx',
        ),
        migrations.RenameField(
            model_name='alert',
            old_name='alert_identifier',
            new_name='identifier',
        ),
        migrations.RenameField(
            model_name='alert',
            old_name='alert_timestamp',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_identifier',
            new_name='identifier',
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['timestamp'], name='timestamp_idx'),
        ),
    ]
